### ISSUE TITLE
增加全局实时监控扫库strm

### ISSUE THREAD

**Issue by GGbond1680** [sjtuross/StrmAssistant#1]
老哥插件很好用，希望可以增加实时监控全部媒体库strm文件就更好了

**Comment by sjtuross** [comment]
之后打算把追更模式和最爱分离，最爱当作一个特殊的媒体库可选择，这样所选的媒体库有新增就会自动扫，存量还是计划任务。

**Comment by sjtuross** [comment]
最新版最爱与追更模式已分离，支持任意选择范围内的媒体库新入库实时提取媒体信息。最爱作为一个特殊的媒体库，处理规则与原先相同。监控是文件系统层面的事，不在插件的设计范围内。
