### ISSUE TITLE
合集无法识别首字母排序

### ISSUE THREAD

**Issue by hfoi589** [sjtuross/StrmAssistant#10]
emby开启“将项目分组到合集中”，启动合集的时候，首字母排序功能无法生效

<img width="954" alt="iShot_2024-10-28_20 11 05" src="https://github.com/user-attachments/assets/ba4f017e-e35b-4ce7-8fb5-67c22b4754a8">
<img width="1208" alt="iShot_2024-10-28_20 10 54" src="https://github.com/user-attachments/assets/00c8cdd2-2699-430f-8320-9e0f8ff4adbb">
<img width="2560" alt="1“ src=”https://github.com/user-attachments/assets/190dcbaf-5fa6-4c2e-948f-78d141394800“>

**Comment by hfoi589** [comment]
![111](https://github.com/user-attachments/assets/407476fa-5af0-42f6-b491-f44799814a4c)

**Comment by sjtuross** [comment]
选中所有合集，做一次搜索缺少的元数据试试
