### ISSUE TITLE
插件安装后为什么会移除我刮削的数据

### ISSUE THREAD

**Issue by 534002646** [sjtuross/StrmAssistant#11]
![image](https://github.com/user-attachments/assets/3945fe47-f995-4b97-a827-78248ed8fc7e)
![image](https://github.com/user-attachments/assets/a7562c17-57fb-49ee-acc2-acde8d2f3306)
![image](https://github.com/user-attachments/assets/65edd14b-e595-432e-9d71-1b61d21b8487)
还有是否会和AutoVersionGrouping插件冲突，这两都有合并版本的功能

**Comment by sjtuross** [comment]
不会和AutoVersionGrouping插件冲突，本插件的合并是基于文件系统判断的，扫库入库时发现同目录即合并，AutoVersionGrouping可以实现进一步的合并

插件没有相关功能会移除你刮削的数据，有什么依据得出这个结论？仅凭那个截图吗？如何复现？
