### ISSUE TITLE
能支持STRM自动连播吗

### ISSUE THREAD

**Issue by qq328508474** [sjtuross/StrmAssistant#13]
EMBY使用STRM文件剧集不能自动播放下一集，这个功能大佬有考虑支持吗？

**Comment by sjtuross** [comment]
我试了下官方iOS app，没有这问题啊，第一集放完会自动播放下一集，这跟是不是strm没什么关系吧，再说这属于客户端的功能范畴。

**Comment by qq328508474** [comment]
> 我试了下官方iOS app，没有这问题啊，第一集放完会自动播放下一集，这跟是不是strm没什么关系吧，再说这属于客户端的功能范畴。

我是影音文件在网盘的，由于网盘放图片、nfo等资源加载速度太慢，而且频繁访问容易封控，所以把图片、nfo、字幕放在本地，然后用工具生成alist网盘列表里的影音文件的strm文件链接，本地strm文件里的内容类似于“http://192.168.1.1/d/xxx.mp4”这样的内容，播放的时候访问网盘，浏览emby网页内容不访问网盘，这样比把所有影音库都放在网盘速度有巨大提高。这的确是Emby的问题，由于本地strm不是影音文件，只是个链接，所以扫库扫不到影音媒体信息，所以剧集没法连播。这不是魔改插件吗，所以问一下，开发插件的大佬有没有解决strm链接的这个连播的方法。

**Comment by sjtuross** [comment]
默认不扫媒体信息，你用插件扫出来不就行了

之前说了不能连播我用官方ios app没有复现，不清楚你说的问题是否具有共性，而且这属于播放器的范畴，非服务端

**Comment by qq328508474** [comment]
> 默认不扫媒体信息，你用插件扫出来不就行了
> 
> 之前说了不能连播我用官方ios app没有复现，不清楚你说的问题是否具有共性，而且这属于播放器的范畴，非服务端

感谢解答，我的STRM内部文本是Http直链开头。我又试了一下，客户端用第三方播放器无法播放下一集，网页的油猴插件embyToLocalPlayer调用播放器也无法下一集，网页播放可以。看来是播放器不能下一集。但是播放器能硬件加速，TV盒子用客户端解码有的高码率视频卡顿，TV盒子软解性能不行，安卓TV盒子只能用手动选下一集，凑合用吧。
