### ISSUE TITLE
非常好用的插件.感谢作者.小疑惑问一下

### ISSUE THREAD

**Issue by ati121** [sjtuross/StrmAssistant#14]
感谢作者.非常好用的搜索功能,太强大了.看了wiki好多都是对strm优化的..我选追更模式.所有设置对本地文件应该都是有效果的吧..是我功能全部打开.有时候扫库挺久的.一个库来回不停的扫(不刷新元数据).独占媒体信息提取这个选项,全是本地文件是开还是不开好呢..多版本好像有些能合并.又些又不能合并.
![22](https://github.com/user-attachments/assets/efd1ae44-9158-405d-be7b-1d093f071671)
![3](https://github.com/user-attachments/assets/77cd5b10-6c96-44e8-a2c7-e2cba70c2b97)

**Comment by sjtuross** [comment]
应该说大部分功能strm和非strm都是可以用的，只是保持低调，否则要叫Emby助手了。

本地文件属于直连，就是非strm，推荐追更搭配独占模式，这样入库Emby只会扫元数据，就快了，提取媒体信息和视频截图的事情就会由追更模式接管多线程运行（每30秒处理一批新增），当然也受限于机能，你可以任务管理器观察ffprobe和ffmpeg的进程数。

多版本合并只适用于同目录的，不同目录的相同电影是不支持的，另外再扫一下库看看，因为是基于文件系统来识别的。
