### ISSUE TITLE
媒体信息提取选库范围没效果

### ISSUE THREAD

**Issue by wc906398139** [sjtuross/StrmAssistant#16]
媒体库范围选择对应的媒体库，实际没选择的也是库也是

**Comment by sjtuross** [comment]
选择无再重新选一下保存。不可能没效果，除非提供详细排查信息。还有如果包含了最爱，那是会去找所有用户的最爱，跟库没关系。

**Comment by sjtuross** [comment]
独占模式是全局的，让Emby只导入元数据，媒体信息可以用计划任务或者追更模式来多线程处理，看下Wiki https://github.com/sjtuross/StrmAssistant/wiki/独占媒体信息提取-(Exclusive-Extract)

**Comment by wc906398139** [comment]
> 独占模式是全局的，让Emby只导入元数据，媒体信息可以用计划任务或者追更模式来多线程处理，看下Wiki [https://github.com/sjtuross/StrmAssistant/wiki/独占媒体信息提取-(Exclusive-Extract)](https://github.com/sjtuross/StrmAssistant/wiki/%E7%8B%AC%E5%8D%A0%E5%AA%92%E4%BD%93%E4%BF%A1%E6%81%AF%E6%8F%90%E5%8F%96-(Exclusive-Extract))
> 
> P.S. 追更模式需更新到今天的最新版

了解了，感谢回复。

**Comment by wc906398139** [comment]
> 独占模式是全局的，让Emby只导入元数据，媒体信息可以用计划任务或者追更模式来多线程处理，看下Wiki [https://github.com/sjtuross/StrmAssistant/wiki/独占媒体信息提取-(Exclusive-Extract)](https://github.com/sjtuross/StrmAssistant/wiki/%E7%8B%AC%E5%8D%A0%E5%AA%92%E4%BD%93%E4%BF%A1%E6%81%AF%E6%8F%90%E5%8F%96-(Exclusive-Extract))
> 
> P.S. 追更模式需更新到今天的最新版

媒体信息提取可以分离么？因为如果是本地文件的话 就不需要

**Comment by sjtuross** [comment]
媒体库范围自己选，本地为什么不需要，本地Emby也是一个个排队做的，插件就是让这个事情多线程，充分利用你的机器资源

**Comment by wc906398139** [comment]
不是说独占模式是全局的么，媒体库范围 我是排除了本地媒体库 还是需要执行插件计划 才能获取信息。本地入库的单线程基本无感（并不是大量），如果插件独占模式是全局的话，我执行计划必须每时每刻都要运行。

**Comment by sjtuross** [comment]
追更模式每30秒处理一批新入库的，一般都是独占搭配追更使用的

独占模式可以按需开启或关闭，暂时不考虑支持媒体库范围

**Comment by wc906398139** [comment]
> 我想起来了，以前独占模式是放在最下面的魔改区域，最近搬到了媒体信息提取区域，那里有媒体库范围选择，所以带来了这个疑问

对的，所以感觉没效果。。

**Comment by sjtuross** [comment]
实现独占模式考虑媒体库范围其实很简单，但是独占模式的设计初衷还包括保护媒体信息，否则strm在刷新元数据时媒体信息就可能丢失，直连虽说不会丢但其实又扫了一遍，也是种资源浪费。独占模式会判断文件是否变化来选择放行与否，这个作用并不与媒体库范围直接绑定，所以说本质上是需求的不一致。我能做的就是在选项说明里写明全局生效，避免误解。

**Comment by wc906398139** [comment]
> 实现独占模式考虑媒体库范围其实很简单，但是独占模式的设计初衷还包括保护媒体信息，否则strm在刷新元数据时媒体信息就可能丢失，直连虽说不会丢但其实又扫了一遍，也是种资源浪费。独占模式会判断文件是否变化来选择放行与否，这个作用并不与媒体库范围直接绑定，所以说本质上是需求的不一致。我能做的就是在选项说明里写明全局生效，避免误解。

库基本完成定型后，基本不会去重新刷元数据的，或者能否做到开关STRM来做到分离。
