### ISSUE TITLE
请问跳过片头片尾可以自动吗

### ISSUE THREAD

**Issue by lwj1113** [sjtuross/StrmAssistant#17]
请问一下这个功能可以自动实现吗，我选择了探测片头片尾，emby设置了自动跳过但是发现还是要手动。

**Comment by sjtuross** [comment]
这个属于播放器功能，非服务端。给你举个例子，Vidhub有这个功能开关。播放器拿到片头片尾数据后决定是提示还是自动。

![image](https://github.com/user-attachments/assets/869173df-d6bd-4644-b5e2-79f3c85aea39)

**Comment by lwj1113** [comment]
维军收到您的邮件了，谢谢~
