### ISSUE TITLE
无法获取电影元数据

### ISSUE THREAD

**Issue by wc906398139** [sjtuross/StrmAssistant#18]
电影是网盘直连 没使用STRM连接，打勾后 就无法获取电影元数据，关闭独占媒体信息提取就能直接获取到。
![11截图_2024-11-05_13-02-31](https://github.com/user-attachments/assets/fd15c0b4-fc4a-43b7-a65c-e756a6b7c4b6)

**Comment by sjtuross** [comment]
独占模式最初的需求就是来自网盘直连用户，测试过没有问题的。我刚刚试了一下也没复现你说的问题，不管元数据来自nfo还是tmdb都是可以获取到的，独占模式只是动态屏蔽ffprobe和ffmpeg，功能上是跟元数据不相干的。

**Comment by wc906398139** [comment]
准确的说应该是卡住 没有去读取tmdb元数据，电影目录是多目录结构。我已经测试多遍都是这个情况，只要把独占媒体信息提取 全部正常获取。

**Comment by sjtuross** [comment]
我找了几个群友测试，也是直连网盘，都说没有问题，猜测是不是你加了媒体库没有手工启动扫库，因为独占模式有个隐藏功能，Wiki中有提到

> 媒体库设置页面，当添加或删除路径时，会自动阻止全局扫库。修改完成之后，手工指定媒体库启动扫库即可。

**Comment by wc906398139** [comment]
> 我找了几个群友测试，也是直连网盘，都说没有问题，猜测是不是你加了媒体库没有手工启动扫库，因为独占模式有个隐藏功能，Wiki中有提到
> 
> > 媒体库设置页面，当添加或删除路径时，会自动阻止全局扫库。修改完成之后，手工指定媒体库启动扫库即可。

我这边测试都是手动指定媒体库文件扫库的

**Comment by sjtuross** [comment]
那就不清楚了，无法复现，要么你日志开调试模式，复现一次，然后提供精确的时间范围，我可以看下

**Comment by wc906398139** [comment]
> 那就不清楚了，无法复现，要么你日志开调试模式，复现一次，然后提供精确的时间范围，我可以看下

我又测试了下，之前的测试的单文件都几千部电影 是出现这个卡住现象，用了几部的文件夹，没有这个问题，我再测试测试看。

**Comment by wc906398139** [comment]
剧集文件 测试了1700 可以获取信息，4000 貌似卡住 3个多小时 无运行

**Comment by wc906398139** [comment]
应该是网盘 掉了 后回复 导致扫库失败。
