### ISSUE TITLE
Strm视频截图

### ISSUE THREAD

**Issue by tsreal** [sjtuross/StrmAssistant#20]
strm库导入emby，若先手贱点击了其中一个视频让emby自动获取到媒体信息，再去计划任务使用助手的提取媒体信息，则会出现仅该视频截图不会生成，是不是因为检测到该视频有媒体信息所以跳过了？为了刮所有封面只好删了媒体库重来。。

**Comment by sjtuross** [comment]
不会，元数据那边没图就会截图。Emby默认是不会扫strm媒体信息的，我也不知道你怎么搞出来的。有问题看日志排查。

**Comment by tsreal** [comment]
感谢大佬秒回，查看日志发现Strm Assistant: MediaInfoExtract这个任务没有扫过我播放的那个视频。
一通乱试之后，我把strm媒体库类型从家庭视频与照片换成电影又正常了。
现在又发现另一个问题：就是分集好像扫不到，我看日志里也只扫cd1，剩下的cd2,cd3,cd4都没检测到
![aaaa](https://github.com/user-attachments/assets/15143a4d-d4f5-4c8c-9088-72f633382768)

**Comment by tsreal** [comment]
倒是通过改名称应该能解决

**Comment by sjtuross** [comment]
分集回头看下，这个比较特殊，到时只要选了附加内容就会包含。

家庭视频这种媒体库没有适配，里面的视频估计没被Emby定义为电影，只是纯视频，估计插件的过滤条件把这种过滤掉了。

**Comment by tsreal** [comment]
感谢解惑

**Comment by sjtuross** [comment]
刚刚测试了一下，勾选这个就会扫cd2/cd3/cd4这种分集，之后我把说明写得再明确一些。

![image](https://github.com/user-attachments/assets/c1005178-6bc8-4bcc-8a34-e909a4270fe7)

关于家庭视频媒体库，计划任务现在是会扫的，追更模式下次更新会修复。

**Comment by tsreal** [comment]
勾选上后分集可以刮了，没仔细看看选项😂非常感谢🙏

**Comment by sjtuross** [comment]
更新版已发布，包含了之前提到的改进，此问题就先关闭了
