### ISSUE TITLE
剧集集标题自动补全

### ISSUE THREAD

**Issue by wc906398139** [sjtuross/StrmAssistant#21]
实际显示没有更改 第 X 集 还是显示的文件名，但是右击编辑元数据标题是修正的 只是显示有问题。

![11截图_2024-11-09_17-02-23](https://github.com/user-attachments/assets/7e4fc344-bb4d-46ac-98b8-d1855a2b0d02)

**Comment by wc906398139** [comment]
季文件查看是没有修改，但是文件再点进去就是修改完成的
![11截图_2024-11-09_18-27-09](https://github.com/user-attachments/assets/ee14eef2-9cf5-4e0a-b9da-a9dd686e5dd5)
![11截图_2024-11-09_18-27-20](https://github.com/user-attachments/assets/a75759fc-5224-4a48-9de8-5d94e96983a6)

**Comment by sjtuross** [comment]
原以为多季纵向跟单季横向显示调用的api参数是一样的，看来不是，下个版本会尝试修复

**Comment by sjtuross** [comment]
试下最新版 https://github.com/sjtuross/StrmAssistant/releases/tag/v1.0.0.38

**Comment by wc906398139** [comment]
> 试下最新版 https://github.com/sjtuross/StrmAssistant/releases/tag/v1.0.0.38

没有问题了
