### ISSUE TITLE
扫不到媒体详细信息

### ISSUE THREAD

**Issue by Nanako718** [sjtuross/StrmAssistant#23]
始终扫不到媒体详细信息

**Comment by Nanako718** [comment]
<img width="880" alt="image" src="https://github.com/user-attachments/assets/4ee64d8c-6fec-46ca-99b0-13d5899e6fdb">
As日志显示扫描到了但是emby没有显示

**Comment by Nanako718** [comment]
<img width="823" alt="image" src="https://github.com/user-attachments/assets/83159ccf-d348-4d0e-83d0-c9f3c1596096">
会扫出来字幕

**Comment by sjtuross** [comment]
as这个扫的功能根插件没有关系，跟插件的追更模式是重叠的功能，二选一就行。

有问题看日志，一般就是emby无法读取strm文件中的路径。

**Comment by Nanako718** [comment]
我用的是软链接。大佬日志在哪儿看

**Comment by sjtuross** [comment]
Emby管理界面，日志，embyserver.txt，下载下来找你扫过片附近的错误信息
