### ISSUE TITLE
有些演员没有详细信息，TMDB上有。运行了刷新演员也没用。请教下这个问题是不是“添加支持从 NFO 导入演员头像链接”影响的，之前正常

### ISSUE THREAD

**Issue by ati121** [sjtuross/StrmAssistant#24]
例如：![122](https://github.com/user-attachments/assets/f5d88af5-b9ee-491b-8ea1-ae9215bacdc3)

**Comment by sjtuross** [comment]
可能吧，nfo导入之前有稳定性问题，后来修复了。刷演员现在默认跳过已是中文，配置文件有个隐藏参数RefreshPersonMode改成FullRefresh就会全刷，或者过几天更新会把简介非中的也纳入默认策略

**Comment by sjtuross** [comment]
更新版已发布，刷演员默认策略会检测演员简介，再跑一次后看看

**Comment by ati121** [comment]
> 更新版已发布，刷演员默认策略会检测演员简介，再跑一次后看看

测试可以显示了。感谢作者辛苦了
