### ISSUE TITLE
无法在docker 映像emby/embyserver_arm64v8中正常使用，丢失功能，无法打✔！！！

### ISSUE THREAD

**Issue by Whys8182** [sjtuross/StrmAssistant#26]
无法在docker 映像emby/embyserver_arm64v8中正常使用，丢失功能，无法打✔！！！
剩余可勾选功能为：
仅支持 STRM
追更模式
包含附加内容
播放行为片头探测

其余功能禁止勾选，请帮忙修复一下！！！

**Comment by sjtuross** [comment]
https://github.com/sjtuross/StrmAssistant/issues/8#issuecomment-2435407002
