### ISSUE TITLE
片头扫描也可以实现多线程吗？

### ISSUE THREAD

**Issue by wc906398139** [sjtuross/StrmAssistant#29]

**Comment by sjtuross** [comment]
这个完全没有api，魔改重写原生的计划任务代价太大。扫片头需要大量的随机io，多线程还会互相抢占资源，结果未必能快多少，特别是网盘场景。除非你本地随机io特别强，一般你同时复制几个文件也未必会快多少。

**Comment by sjtuross** [comment]
瓶颈在网速。魔改代价太大，能否魔改都是随缘，我又不是luke想怎么改就怎么改。

**Comment by sjtuross** [comment]
刚刚看了下，有可能可以利用多线程媒体信息提取的过程预处理得到声纹文件，然后再跑原生的扫片头估计就能很快完成

**Comment by wc906398139** [comment]
> 刚刚看了下，有可能可以利用多线程媒体信息提取的过程预处理得到声纹文件，然后再跑原生的扫片头估计就能很快完成

这样也不错，能减少多次读取一个文件，看看可实施嘛

**Comment by sjtuross** [comment]
需要做一些实验

**Comment by sjtuross** [comment]
搞定了 https://github.com/sjtuross/StrmAssistant/releases/tag/v1.0.0.41

操作说明看Wiki https://github.com/sjtuross/StrmAssistant/wiki/片头探测-‐-原生增强

**Comment by wc906398139** [comment]
> 搞定了 https://github.com/sjtuross/StrmAssistant/releases/tag/v1.0.0.41
> 
> 操作说明看Wiki [https://github.com/sjtuross/StrmAssistant/wiki/片头探测-‐-原生增强](https://github.com/sjtuross/StrmAssistant/wiki/%E7%89%87%E5%A4%B4%E6%8E%A2%E6%B5%8B-%E2%80%90-%E5%8E%9F%E7%94%9F%E5%A2%9E%E5%BC%BA)

感谢 扫完后测试一下

**Comment by sjtuross** [comment]
41版正式发了，你得手工更新，因为版本号一样。现在提取完声纹后会自动运行原生的那个计划任务导入，这样就全自动了。另外媒体库范围同时作用于原生片头探测的计划任务。

**Comment by wc906398139** [comment]
> 41版正式发了，做了些修改。现在提取完声纹后会自动运行原生的那个计划任务导入，这样就全自动了。另外媒体库范围同时作用于原生片头探测的计划任务。

由于独占媒体信息提取是全局下，我没选择勾选，那么原生扫描的媒体库信息第一个出来后 会直接触发原生片头探测的计划任务么？

**Comment by sjtuross** [comment]
不会触发，不是所有人都用Emby扫片头的，这两者没有相联性。跟独占模式也没有关系。将来可能会改造追更模式，包含元数据，媒体信息，片头，到时想扫就全选。

**Comment by wc906398139** [comment]
> 不会触发，不是所有人都用Emby扫片头的，这两者没有相联性。跟独占模式也没有关系。将来可能会改造追更模式，包含元数据，媒体信息，片头，到时想扫就全选。

了解了
