### ISSUE TITLE
神医，原语言海报这个功能可以增加支持一下FanArt吗？

### ISSUE THREAD

**Issue by entaroartanis114514** [sjtuross/StrmAssistant#3]
因为有时候FanArt的海报相比TMDB的更好看点 也更清晰一些。

**Comment by sjtuross** [comment]
Fanart api返回的json数据里没有片子的原语言，只有tmdbid，Emby也不存原语言，除非再调用一次tmdb api去获得。另外Fanart各语种的海报我看并不多，所以就做了一个简单的逻辑，基于原语言片名判断中日韩英来选择海报，下个版本你可以试试。另外还支持了TVDB的原语言海报，Wiki也同步更新了。

**Comment by entaroartanis114514** [comment]
还得是神医,妙手回春。
tvdb都支持了，这下满足了。
