### ISSUE TITLE
关于演员刮削

### ISSUE THREAD

**Issue by wc906398139** [sjtuross/StrmAssistant#30]
剧集 emby默认演员刮削都是 已最新一季的演员表来刮削，这样导致很多演员刮削不完整 有些甚至出现一个演员元数据。如果国产剧集很多连续的1 2 3季 演员不相同 无法完美。
如：琅琊榜 1是胡歌 2是黄晓明
https://www.themoviedb.org/tv/64197-nirvana-in-fire

那么emby默认刮削就是第二部的黄晓明演员表，遗漏第一部的。

看看能不能把所有剧集的演员全部刮削。
![11截图_2024-11-14_00-04-53](https://github.com/user-attachments/assets/a435fbf1-1285-4942-9b52-92efaa060a39)

**Comment by sjtuross** [comment]
这个我有空研究一下

**Comment by sjtuross** [comment]
看了下，本质上是tmdb整个系列series返回的元数据的问题，Emby只是原样显示。一种解决方式是魔改返回给UI的演职人员的数据，合并各季的演员，但点击或者搜索演员比如胡歌，还是无法关联到琅琊榜整个系列。而且不确定这个问题是否具有共性，就是说是否所有tmdb多季的剧集都有这个问题。

https://api.themoviedb.org/3/tv/64197?api_key=f6bd687ffa63cd282b6ff2c6877f2669&append_to_response=credits&language=zh-CN

```
{
  "adult": false,
  "backdrop_path": "/4pBohJyXnAf7yvzyMTD1953RIjY.jpg",
  "created_by": [],
  "episode_run_time": [
    45
  ],
  "first_air_date": "2015-09-19",
  "genres": [
    {
      "id": 18,
      "name": "剧情"
    }
  ],
  "homepage": "https://www.iqiyi.com/a_19rrhc0u75.html",
  "id": 64197,
  "in_production": false,
  "languages": [
    "zh"
  ],
  "last_air_date": "2018-02-12",
  "last_episode_to_air": {
    "id": 1436965,
    "name": "平定叛乱 告别朝堂",
    "overview": "叛军仓皇溃败，萧平旌带着萧元时攻入内殿，萧平旌斥责萧元启心无家国之念才是他失败的根本。两人决一死战，萧元启又使出金乌水月，剑尖却打在萧平旌左手的手环上，萧元启战败被刺死。虽然陛下再三挽留，但萧平旌还是决定离开朝堂。离开金陵城，萧平旌看见林奚站在半坡凉亭之上等他，萧平旌欢喜地将她抱起，两人纵马前行。",
    "vote_average": 0.0,
    "vote_count": 0,
    "air_date": "2018-02-12",
    "episode_number": 50,
    "episode_type": "finale",
    "production_code": "",
    "runtime": 45,
    "season_number": 2,
    "show_id": 64197,
    "still_path": null
  },
  "name": "琅琊榜",
  "next_episode_to_air": null,
  "networks": [
    {
      "id": 455,
      "logo_path": "/5LU9zEP1SredmscM25lv7Z1xW3y.png",
      "name": "Beijing Television",
      "origin_country": "CN"
    },
    {
      "id": 1056,
      "logo_path": "/neufSFU0ZrXxA3c0JRNpuNXzLdx.png",
      "name": "Dragon TV",
      "origin_country": "CN"
    },
    {
      "id": 1330,
      "logo_path": "/fNxBFqWr7eWEgNeBDvvCxsSItXx.png",
      "name": "iQiyi",
      "origin_country": "CN"
    }
  ],
  "number_of_episodes": 104,
  "number_of_seasons": 2,
  "origin_country": [
    "CN"
  ],
  "original_language": "zh",
  "original_name": "琅琊榜",
  "overview": "十二年前七万赤焰军被奸人所害导致全军覆没，冤死梅岭，只剩少帅林殊侥幸生还。十二年后林殊改头换面化身“麒麟才子”梅长苏，建立江左盟，以“琅琊榜”第一才子的身份重返帝都。梅长苏背负血海深仇，暗中帮助昔日挚友靖王周旋于太子与誉王的斗争之中，同时又遇到了昔日未婚妻——云南王郡主穆霓凰却不能相见。梅长苏以病弱之躯为昭雪冤案、为振兴河山，踏上了一条黑暗又惊心动魄的夺嫡之路……",
  "popularity": 138.926,
  "poster_path": "/pzDC9rdyJhGdgVGoYuAj8LTHBtJ.jpg",
  "production_companies": [
    {
      "id": 60279,
      "logo_path": "/ktG4Vckkhc0yOkxYLVW0krygf08.png",
      "name": "Shandong Film & TV Group",
      "origin_country": "CN"
    },
    {
      "id": 148869,
      "logo_path": "/1uiCvFIkqy90sifkKMAMFF2efUi.png",
      "name": "Daylight Entertainment Co., Ltd.",
      "origin_country": "CN"
    },
    {
      "id": 98983,
      "logo_path": null,
      "name": "Shanghai Ruyi Film & TV Production",
      "origin_country": "CN"
    }
  ],
  "production_countries": [
    {
      "iso_3166_1": "CN",
      "name": "China"
    }
  ],
  "seasons": [
    {
      "air_date": "2015-09-19",
      "episode_count": 54,
      "id": 71492,
      "name": "第1季",
      "overview": "十二年前七万赤焰军被奸人所害导致全军覆没，冤死梅岭，只剩少帅林殊侥幸生还。十二年后林殊改头换面化身“麒麟才子”梅长苏，建立江左盟，以“琅琊榜”第一才子的身份重返帝都。梅长苏背负血海深仇，暗中帮助昔日挚友靖王周旋于太子与誉王的斗争之中，同时又遇到了昔日未婚妻——云南王郡主穆霓凰却不能相见。梅长苏以病弱之躯为昭雪冤案、为振兴河山，踏上了一条黑暗又惊心动魄的夺嫡之路……",
      "poster_path": "/2ILzpYoHgHztVKZa2RkZdqUS9DA.jpg",
      "season_number": 1,
      "vote_average": 0.0
    },
    {
      "air_date": "2017-12-21",
      "episode_count": 50,
      "id": 97862,
      "name": "第2季 风起长林",
      "overview": "大梁朝局安稳，但边境战火不断，守护大梁北境的长林军屡获军功，因梁帝（刘钧饰）心慈体弱而太子年幼，荀皇后（梅婷饰）与其胞兄荀白水（毕彦君饰）恐长林王府功高盖主，被伪潜入宫廷来大梁的夜秦人濮阳缨（郭京飞饰）利用，陷害长林王萧庭生（孙淳饰）父子三人，不仅在一次北境交战中断掉前线补给，致长林世子萧平章（黄晓明饰）身受重伤，更在京城制造大规模疫情。追查过程时，平章与其弟萧平旌（刘昊然饰）先后中毒，此时北境急危，平章放弃救治，奔赴前线支援后毒发而亡。平旌为国境安宁，在长兄牺牲后即刻驻守边疆。梁帝死后令庭生辅政，荀白水扶植萧元启（吴昊宸饰）掌握兵权以对抗长林王府，在他们的诡计之下，平旌为了百姓反落得抗旨的罪名，庭生逝世长林府封府，长林军编制被撤。元启暗地里与已成为东海国主的舅舅墨淄侯（成泰燊饰）勾结，卖国谋逆。隐居多年的平旌危急之中起兵勤王，成功挫败萧元启的阴谋。待到大梁边境整顿完毕，平旌再次离开金陵归隐。",
      "poster_path": "/wh5AuqYsAFMXZdWv4Rkl5pvvCWG.jpg",
      "season_number": 2,
      "vote_average": 0.0
    }
  ],
  "spoken_languages": [
    {
      "english_name": "Mandarin",
      "iso_639_1": "zh",
      "name": "普通话"
    }
  ],
  "status": "Ended",
  "tagline": "一卷风云琅琊榜，囊尽天下奇英才。",
  "type": "Scripted",
  "vote_average": 9.1,
  "vote_count": 52,
  "credits": {
    "cast": [
      {
        "adult": false,
        "gender": 2,
        "id": 109434,
        "known_for_department": "Acting",
        "name": "黄晓明",
        "original_name": "黃曉明",
        "popularity": 15.121,
        "profile_path": "/pXIc99hxrDGOpXQChy7SM03YXpA.jpg",
        "character": "Xiao Pingzhang",
        "credit_id": "655c78f97f054018d344c49c",
        "order": 22
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1573819,
        "known_for_department": "Acting",
        "name": "刘昊然",
        "original_name": "劉昊然",
        "popularity": 4.969,
        "profile_path": "/8BQu6ypn14E8s2DYzyeMUPlVR3K.jpg",
        "character": "Xiao Pingjing",
        "credit_id": "655c79097f054018d6f5bc99",
        "order": 23
      },
      {
        "adult": false,
        "gender": 1,
        "id": 1173214,
        "known_for_department": "Acting",
        "name": "佟丽娅",
        "original_name": "佟麗婭",
        "popularity": 11.672,
        "profile_path": "/q9BsyBMfYgZoQy41SKpVw8RrGOY.jpg",
        "character": "Meng Qianxue",
        "credit_id": "655c7915b5400214d3ccb47d",
        "order": 24
      },
      {
        "adult": false,
        "gender": 1,
        "id": 1376103,
        "known_for_department": "Acting",
        "name": "张慧雯",
        "original_name": "張慧雯",
        "popularity": 7.492,
        "profile_path": "/4bwN8AapFZhLp8vhtVzLmUrA6Lg.jpg",
        "character": "Lin Xi",
        "credit_id": "655c794e10923000e1437f75",
        "order": 25
      },
      {
        "adult": false,
        "gender": 2,
        "id": 150152,
        "known_for_department": "Acting",
        "name": "孙淳",
        "original_name": "孫淳",
        "popularity": 3.815,
        "profile_path": "/3a9s6XlvOjWmGAzcdqcfXAakFBe.jpg",
        "character": "Xiao Tingsheng",
        "credit_id": "655c795910923000e1437f7a",
        "order": 26
      },
      {
        "adult": false,
        "gender": 2,
        "id": 2296980,
        "known_for_department": "Acting",
        "name": "吴昊宸",
        "original_name": "Wu Haochen",
        "popularity": 1.861,
        "profile_path": "/vJ32X3fGchjNk8UaHebX0WyHBx9.jpg",
        "character": "Xiao Yuanqi",
        "credit_id": "655c79653d745400ada26ff2",
        "order": 27
      },
      {
        "adult": false,
        "gender": 1,
        "id": 131343,
        "known_for_department": "Acting",
        "name": "梅婷",
        "original_name": "梅婷",
        "popularity": 3.635,
        "profile_path": "/bXM7E3c6aLJc4yzH5vhCkzwurTz.jpg",
        "character": "Empress Xun",
        "credit_id": "655c797c10923000ab49a230",
        "order": 28
      },
      {
        "adult": false,
        "gender": 2,
        "id": 2027663,
        "known_for_department": "Acting",
        "name": "张博",
        "original_name": "张博",
        "popularity": 3.689,
        "profile_path": "/1eGx4N2YD0kFlX9QsYCGDVYtDmq.jpg",
        "character": "Xun Feizhan",
        "credit_id": "655c79883d7454013be60af5",
        "order": 29
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1353688,
        "known_for_department": "Acting",
        "name": "郭京飞",
        "original_name": "Guo Jingfei",
        "popularity": 5.437,
        "profile_path": "/xNyi4uOHKAqCgW7JhV5MPn5BG88.jpg",
        "character": "Pu Yangying",
        "credit_id": "655c799353866e00abaeaf72",
        "order": 30
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1613668,
        "known_for_department": "Acting",
        "name": "刘钧",
        "original_name": "刘钧",
        "popularity": 2.532,
        "profile_path": "/q1tYa7yrHGBWBLHL53cApImRWLq.jpg",
        "character": "Emperor Liang",
        "credit_id": "655c799e1092300138c805e1",
        "order": 31
      },
      {
        "adult": false,
        "gender": 1,
        "id": 1696484,
        "known_for_department": "Acting",
        "name": "乔欣",
        "original_name": "喬欣",
        "popularity": 10.059,
        "profile_path": "/3uDhDKGoqF1r8Mp3NEm5562UpYx.jpg",
        "character": "Xun Anru",
        "credit_id": "655c79a9b5400214d07187c7",
        "order": 32
      }
    ],
    "crew": [
      {
        "adult": false,
        "gender": 2,
        "id": 1494556,
        "known_for_department": "Directing",
        "name": "孔笙",
        "original_name": "Kong Sheng",
        "popularity": 1.083,
        "profile_path": "/tuvsHtbfhPJH7qDwyQg686kVfKi.jpg",
        "credit_id": "5a72aa0c0e0a266433004f8c",
        "department": "Directing",
        "job": "Director"
      },
      {
        "adult": false,
        "gender": 1,
        "id": 1885413,
        "known_for_department": "Writing",
        "name": "海宴",
        "original_name": "Yan Hai",
        "popularity": 0.252,
        "profile_path": "/9f2RP9jDmljlDMV1IoCaCCcjgZ1.jpg",
        "credit_id": "59b56b94c3a3680252000005",
        "department": "Writing",
        "job": "Writer"
      },
      {
        "adult": false,
        "gender": 2,
        "id": 1805546,
        "known_for_department": "Directing",
        "name": "李雪",
        "original_name": "李雪",
        "popularity": 2.583,
        "profile_path": null,
        "credit_id": "5cd3ab23c3a3680983d87952",
        "department": "Directing",
        "job": "Director"
      }
    ]
  }
}
```

**Comment by wc906398139** [comment]
> 看了下，本质上是tmdb整个系列series返回的元数据的问题，Emby只是原样显示。一种解决方式是魔改返回给UI的演职人员的数据，合并各季的演员，但点击或者搜索演员比如胡歌，还是无法关联到琅琊榜整个系列。而且不确定这个问题是否具有共性，就是说是否所有tmdb多季的剧集都有这个问题。
> 
> https://api.themoviedb.org/3/tv/64197?api_key=f6bd687ffa63cd282b6ff2c6877f2669&append_to_response=credits&language=zh-CN
> 
> ```
> {
>   "adult": false,
>   "backdrop_path": "/4pBohJyXnAf7yvzyMTD1953RIjY.jpg",
>   "created_by": [],
>   "episode_run_time": [
>     45
>   ],
>   "first_air_date": "2015-09-19",
>   "genres": [
>     {
>       "id": 18,
>       "name": "剧情"
>     }
>   ],
>   "homepage": "https://www.iqiyi.com/a_19rrhc0u75.html",
>   "id": 64197,
>   "in_production": false,
>   "languages": [
>     "zh"
>   ],
>   "last_air_date": "2018-02-12",
>   "last_episode_to_air": {
>     "id": 1436965,
>     "name": "平定叛乱 告别朝堂",
>     "overview": "叛军仓皇溃败，萧平旌带着萧元时攻入内殿，萧平旌斥责萧元启心无家国之念才是他失败的根本。两人决一死战，萧元启又使出金乌水月，剑尖却打在萧平旌左手的手环上，萧元启战败被刺死。虽然陛下再三挽留，但萧平旌还是决定离开朝堂。离开金陵城，萧平旌看见林奚站在半坡凉亭之上等他，萧平旌欢喜地将她抱起，两人纵马前行。",
>     "vote_average": 0.0,
>     "vote_count": 0,
>     "air_date": "2018-02-12",
>     "episode_number": 50,
>     "episode_type": "finale",
>     "production_code": "",
>     "runtime": 45,
>     "season_number": 2,
>     "show_id": 64197,
>     "still_path": null
>   },
>   "name": "琅琊榜",
>   "next_episode_to_air": null,
>   "networks": [
>     {
>       "id": 455,
>       "logo_path": "/5LU9zEP1SredmscM25lv7Z1xW3y.png",
>       "name": "Beijing Television",
>       "origin_country": "CN"
>     },
>     {
>       "id": 1056,
>       "logo_path": "/neufSFU0ZrXxA3c0JRNpuNXzLdx.png",
>       "name": "Dragon TV",
>       "origin_country": "CN"
>     },
>     {
>       "id": 1330,
>       "logo_path": "/fNxBFqWr7eWEgNeBDvvCxsSItXx.png",
>       "name": "iQiyi",
>       "origin_country": "CN"
>     }
>   ],
>   "number_of_episodes": 104,
>   "number_of_seasons": 2,
>   "origin_country": [
>     "CN"
>   ],
>   "original_language": "zh",
>   "original_name": "琅琊榜",
>   "overview": "十二年前七万赤焰军被奸人所害导致全军覆没，冤死梅岭，只剩少帅林殊侥幸生还。十二年后林殊改头换面化身“麒麟才子”梅长苏，建立江左盟，以“琅琊榜”第一才子的身份重返帝都。梅长苏背负血海深仇，暗中帮助昔日挚友靖王周旋于太子与誉王的斗争之中，同时又遇到了昔日未婚妻——云南王郡主穆霓凰却不能相见。梅长苏以病弱之躯为昭雪冤案、为振兴河山，踏上了一条黑暗又惊心动魄的夺嫡之路……",
>   "popularity": 138.926,
>   "poster_path": "/pzDC9rdyJhGdgVGoYuAj8LTHBtJ.jpg",
>   "production_companies": [
>     {
>       "id": 60279,
>       "logo_path": "/ktG4Vckkhc0yOkxYLVW0krygf08.png",
>       "name": "Shandong Film & TV Group",
>       "origin_country": "CN"
>     },
>     {
>       "id": 148869,
>       "logo_path": "/1uiCvFIkqy90sifkKMAMFF2efUi.png",
>       "name": "Daylight Entertainment Co., Ltd.",
>       "origin_country": "CN"
>     },
>     {
>       "id": 98983,
>       "logo_path": null,
>       "name": "Shanghai Ruyi Film & TV Production",
>       "origin_country": "CN"
>     }
>   ],
>   "production_countries": [
>     {
>       "iso_3166_1": "CN",
>       "name": "China"
>     }
>   ],
>   "seasons": [
>     {
>       "air_date": "2015-09-19",
>       "episode_count": 54,
>       "id": 71492,
>       "name": "第1季",
>       "overview": "十二年前七万赤焰军被奸人所害导致全军覆没，冤死梅岭，只剩少帅林殊侥幸生还。十二年后林殊改头换面化身“麒麟才子”梅长苏，建立江左盟，以“琅琊榜”第一才子的身份重返帝都。梅长苏背负血海深仇，暗中帮助昔日挚友靖王周旋于太子与誉王的斗争之中，同时又遇到了昔日未婚妻——云南王郡主穆霓凰却不能相见。梅长苏以病弱之躯为昭雪冤案、为振兴河山，踏上了一条黑暗又惊心动魄的夺嫡之路……",
>       "poster_path": "/2ILzpYoHgHztVKZa2RkZdqUS9DA.jpg",
>       "season_number": 1,
>       "vote_average": 0.0
>     },
>     {
>       "air_date": "2017-12-21",
>       "episode_count": 50,
>       "id": 97862,
>       "name": "第2季 风起长林",
>       "overview": "大梁朝局安稳，但边境战火不断，守护大梁北境的长林军屡获军功，因梁帝（刘钧饰）心慈体弱而太子年幼，荀皇后（梅婷饰）与其胞兄荀白水（毕彦君饰）恐长林王府功高盖主，被伪潜入宫廷来大梁的夜秦人濮阳缨（郭京飞饰）利用，陷害长林王萧庭生（孙淳饰）父子三人，不仅在一次北境交战中断掉前线补给，致长林世子萧平章（黄晓明饰）身受重伤，更在京城制造大规模疫情。追查过程时，平章与其弟萧平旌（刘昊然饰）先后中毒，此时北境急危，平章放弃救治，奔赴前线支援后毒发而亡。平旌为国境安宁，在长兄牺牲后即刻驻守边疆。梁帝死后令庭生辅政，荀白水扶植萧元启（吴昊宸饰）掌握兵权以对抗长林王府，在他们的诡计之下，平旌为了百姓反落得抗旨的罪名，庭生逝世长林府封府，长林军编制被撤。元启暗地里与已成为东海国主的舅舅墨淄侯（成泰燊饰）勾结，卖国谋逆。隐居多年的平旌危急之中起兵勤王，成功挫败萧元启的阴谋。待到大梁边境整顿完毕，平旌再次离开金陵归隐。",
>       "poster_path": "/wh5AuqYsAFMXZdWv4Rkl5pvvCWG.jpg",
>       "season_number": 2,
>       "vote_average": 0.0
>     }
>   ],
>   "spoken_languages": [
>     {
>       "english_name": "Mandarin",
>       "iso_639_1": "zh",
>       "name": "普通话"
>     }
>   ],
>   "status": "Ended",
>   "tagline": "一卷风云琅琊榜，囊尽天下奇英才。",
>   "type": "Scripted",
>   "vote_average": 9.1,
>   "vote_count": 52,
>   "credits": {
>     "cast": [
>       {
>         "adult": false,
>         "gender": 2,
>         "id": 109434,
>         "known_for_department": "Acting",
>         "name": "黄晓明",
>         "original_name": "黃曉明",
>         "popularity": 15.121,
>         "profile_path": "/pXIc99hxrDGOpXQChy7SM03YXpA.jpg",
>         "character": "Xiao Pingzhang",
>         "credit_id": "655c78f97f054018d344c49c",
>         "order": 22
>       },
>       {
>         "adult": false,
>         "gender": 2,
>         "id": 1573819,
>         "known_for_department": "Acting",
>         "name": "刘昊然",
>         "original_name": "劉昊然",
>         "popularity": 4.969,
>         "profile_path": "/8BQu6ypn14E8s2DYzyeMUPlVR3K.jpg",
>         "character": "Xiao Pingjing",
>         "credit_id": "655c79097f054018d6f5bc99",
>         "order": 23
>       },
>       {
>         "adult": false,
>         "gender": 1,
>         "id": 1173214,
>         "known_for_department": "Acting",
>         "name": "佟丽娅",
>         "original_name": "佟麗婭",
>         "popularity": 11.672,
>         "profile_path": "/q9BsyBMfYgZoQy41SKpVw8RrGOY.jpg",
>         "character": "Meng Qianxue",
>         "credit_id": "655c7915b5400214d3ccb47d",
>         "order": 24
>       },
>       {
>         "adult": false,
>         "gender": 1,
>         "id": 1376103,
>         "known_for_department": "Acting",
>         "name": "张慧雯",
>         "original_name": "張慧雯",
>         "popularity": 7.492,
>         "profile_path": "/4bwN8AapFZhLp8vhtVzLmUrA6Lg.jpg",
>         "character": "Lin Xi",
>         "credit_id": "655c794e10923000e1437f75",
>         "order": 25
>       },
>       {
>         "adult": false,
>         "gender": 2,
>         "id": 150152,
>         "known_for_department": "Acting",
>         "name": "孙淳",
>         "original_name": "孫淳",
>         "popularity": 3.815,
>         "profile_path": "/3a9s6XlvOjWmGAzcdqcfXAakFBe.jpg",
>         "character": "Xiao Tingsheng",
>         "credit_id": "655c795910923000e1437f7a",
>         "order": 26
>       },
>       {
>         "adult": false,
>         "gender": 2,
>         "id": 2296980,
>         "known_for_department": "Acting",
>         "name": "吴昊宸",
>         "original_name": "Wu Haochen",
>         "popularity": 1.861,
>         "profile_path": "/vJ32X3fGchjNk8UaHebX0WyHBx9.jpg",
>         "character": "Xiao Yuanqi",
>         "credit_id": "655c79653d745400ada26ff2",
>         "order": 27
>       },
>       {
>         "adult": false,
>         "gender": 1,
>         "id": 131343,
>         "known_for_department": "Acting",
>         "name": "梅婷",
>         "original_name": "梅婷",
>         "popularity": 3.635,
>         "profile_path": "/bXM7E3c6aLJc4yzH5vhCkzwurTz.jpg",
>         "character": "Empress Xun",
>         "credit_id": "655c797c10923000ab49a230",
>         "order": 28
>       },
>       {
>         "adult": false,
>         "gender": 2,
>         "id": 2027663,
>         "known_for_department": "Acting",
>         "name": "张博",
>         "original_name": "张博",
>         "popularity": 3.689,
>         "profile_path": "/1eGx4N2YD0kFlX9QsYCGDVYtDmq.jpg",
>         "character": "Xun Feizhan",
>         "credit_id": "655c79883d7454013be60af5",
>         "order": 29
>       },
>       {
>         "adult": false,
>         "gender": 2,
>         "id": 1353688,
>         "known_for_department": "Acting",
>         "name": "郭京飞",
>         "original_name": "Guo Jingfei",
>         "popularity": 5.437,
>         "profile_path": "/xNyi4uOHKAqCgW7JhV5MPn5BG88.jpg",
>         "character": "Pu Yangying",
>         "credit_id": "655c799353866e00abaeaf72",
>         "order": 30
>       },
>       {
>         "adult": false,
>         "gender": 2,
>         "id": 1613668,
>         "known_for_department": "Acting",
>         "name": "刘钧",
>         "original_name": "刘钧",
>         "popularity": 2.532,
>         "profile_path": "/q1tYa7yrHGBWBLHL53cApImRWLq.jpg",
>         "character": "Emperor Liang",
>         "credit_id": "655c799e1092300138c805e1",
>         "order": 31
>       },
>       {
>         "adult": false,
>         "gender": 1,
>         "id": 1696484,
>         "known_for_department": "Acting",
>         "name": "乔欣",
>         "original_name": "喬欣",
>         "popularity": 10.059,
>         "profile_path": "/3uDhDKGoqF1r8Mp3NEm5562UpYx.jpg",
>         "character": "Xun Anru",
>         "credit_id": "655c79a9b5400214d07187c7",
>         "order": 32
>       }
>     ],
>     "crew": [
>       {
>         "adult": false,
>         "gender": 2,
>         "id": 1494556,
>         "known_for_department": "Directing",
>         "name": "孔笙",
>         "original_name": "Kong Sheng",
>         "popularity": 1.083,
>         "profile_path": "/tuvsHtbfhPJH7qDwyQg686kVfKi.jpg",
>         "credit_id": "5a72aa0c0e0a266433004f8c",
>         "department": "Directing",
>         "job": "Director"
>       },
>       {
>         "adult": false,
>         "gender": 1,
>         "id": 1885413,
>         "known_for_department": "Writing",
>         "name": "海宴",
>         "original_name": "Yan Hai",
>         "popularity": 0.252,
>         "profile_path": "/9f2RP9jDmljlDMV1IoCaCCcjgZ1.jpg",
>         "credit_id": "59b56b94c3a3680252000005",
>         "department": "Writing",
>         "job": "Writer"
>       },
>       {
>         "adult": false,
>         "gender": 2,
>         "id": 1805546,
>         "known_for_department": "Directing",
>         "name": "李雪",
>         "original_name": "李雪",
>         "popularity": 2.583,
>         "profile_path": null,
>         "credit_id": "5cd3ab23c3a3680983d87952",
>         "department": "Directing",
>         "job": "Director"
>       }
>     ]
>   }
> }
> ```

这个问题是所有剧集都这样的。意思就算魔改合并 演员也无法关联剧集么？

**Comment by sjtuross** [comment]
我的意思是通过UI魔改的方式不会完美。共性问题那还是要想办法从根本上解决，就是要把各季的演员都导入到整个节目系列上。

**Comment by wc906398139** [comment]
> 我的意思是通过UI魔改的方式不会完美。共性问题那还是要想办法从根本上解决，就是要把各季的演员都导入到整个节目系列上。

了解了

**Comment by sjtuross** [comment]
发了个预览版 https://github.com/sjtuross/StrmAssistant/releases/tag/v1.0.0.42

实现了导入TMDB季的演职人员，现在季的页面底部也会显示演职人员，同时更新节目系列的演职人员为各季合并，按照每季的演员次序交替排列，具体说明和效果看下 https://github.com/sjtuross/StrmAssistant/wiki/中文演员-(Chinese-Actor)

确保媒体库开启TMDB元数据刮削器，然后刷新琅琊榜的元数据看结果。

**Comment by wc906398139** [comment]
> 发了个预览版 https://github.com/sjtuross/StrmAssistant/releases/tag/v1.0.0.42
> 
> 实现了导入TMDB季的演职人员，现在季的页面底部也会显示演职人员，同时更新节目系列的演职人员为各季合并，按照每季的演员次序交替排列，具体说明和效果看下 [https://github.com/sjtuross/StrmAssistant/wiki/中文演员-(Chinese-Actor)](https://github.com/sjtuross/StrmAssistant/wiki/%E4%B8%AD%E6%96%87%E6%BC%94%E5%91%98-(Chinese-Actor))
> 
> 确保媒体库开启TMDB元数据刮削器，然后刷新琅琊榜的元数据看结果。

非常棒，感谢。
