### ISSUE TITLE
神医,关于变相多线程入库稳定触发的一个问题？

### ISSUE THREAD

**Issue by entaroartanis114514** [sjtuross/StrmAssistant#32]
我的配置除了 **播放行为片头探测  仅支持strm 使用替代 TMDB API 地址** 其它全开了。
神医可以让emby自动在媒体信息提取完成之前不扫描片头和缩略图章节图，必须等待媒体信息出来后再扫吗？
因为一次性下太多的话，还要等所有的影片都扫出来媒体信息才能再开计划任务，不然就要删除影片重启emby然后重新入库，有点麻烦。

变相多入库第一步是获取元数据然后是多线程提取媒体信息以及视频截图，但获取元数据后媒体信息还没出来的那段时间，计划任务的扫描片头或者截章节图正好运行会导致视频不论播放多长时间退出后会直接显示已播放。
而且文件夹内的章节图和缩略图可以正常看但也在emby播放器的进度条里显示不了。
这种情况只有删除媒体文件然后重启emby再重新入库，保证媒体信息出来之前不扫描片头和缩略图章节图。

> 这是章节图和缩略图已扫好，以及目前属于未播放

![image](https://github.com/user-attachments/assets/d0cc8c55-6d07-498c-9503-21aae47a2607)

> 无缩略图以及目前的播放时长
![image](https://github.com/user-attachments/assets/071f6a3c-3e33-45e3-b961-7a07d57476fd)

> 退出后会直接显示已播放
![image](https://github.com/user-attachments/assets/1056599e-424e-45ea-8ece-b5596c591634)

>这个是等待媒体信息出来后再扫章节图缩略图就正常，而且正常和不正常的进度条颜色也不同
![image](https://github.com/user-attachments/assets/0e93f175-432f-4df7-82f0-de1ec3062a76)

还有媒体信息提取那里的媒体库范围，留空包含所有。
但我这里实际情况并没有留空包含所有，需要手动指定库，不然媒体信息提取还需要增加一个计划任务，并把片头和缩略图章节图 添加媒体时提取关闭 手动开启计划任务。

**Comment by entaroartanis114514** [comment]
> 补充一下
神医，我忘说了我是4.9.0.30版本，可能是测试版的问题？
神医，晚点回家后我看能不能上传一个视频，我这里是稳定触发的。

> 第一个问题
神医，多线程入库会先出来元数据，媒体信息要稍等一下才能出来，就在没出来的那个时间内开启扫描缩略图章节图或者片头就会出问题。
导致无论播放多长时间退出后都会直接显示已播放和emby里已经扫好但出不来缩略图。
具体原因我也弄不太清楚，我这触发都是在媒体信息没出来的那段时间 扫描章节图缩略图或者片头就会出事。
我这里媒体信息没出来前可以开启扫描章节图缩略图或者片头的计划任务的。

> 第二个问题
神医，我这触发这个问题后是删掉后重启emby再重新入库保证媒体信息出来前不要扫章节图缩略图和片头。

> 第三个问题
文件夹内thumb打开正常，bif我之前提过来过几个图片也正常的 ，数据库里的章节标记我确实还没看。
就是在emby里播放进度那里不显示缩略图和无论播放多长时间退出后都会直接显示已播放

> 第四个问题
这个是个另外的问题，不好意思神医，我这个我回去再看一下。
我记得之前留空出不来媒体信息，需要再开个计划任务

**Comment by entaroartanis114514** [comment]
> 我的配置除了 **播放行为片头探测 仅支持strm 使用替代 TMDB API 地址** 其它全开了。 神医可以让emby自动在媒体信息提取完成之前不扫描片头和缩略图章节图，必须等待媒体信息出来后再扫吗？ 因为一次性下太多的话，还要等所有的影片都扫出来媒体信息才能再开计划任务，不然就要删除影片重启emby然后重新入库，有点麻烦。
> 
> 变相多入库第一步是获取元数据然后是多线程提取媒体信息以及视频截图，但获取元数据后媒体信息还没出来的那段时间，计划任务的扫描片头或者截章节图正好运行会导致视频不论播放多长时间退出后会直接显示已播放。 而且文件夹内的章节图和缩略图可以正常看但也在emby播放器的进度条里显示不了。 这种情况只有删除媒体文件然后重启emby再重新入库，保证媒体信息出来之前不扫描片头和缩略图章节图。
> 
> > 这是章节图和缩略图已扫好，以及目前属于未播放
> 
> ![image](https://private-user-images.githubusercontent.com/155457237/387363051-d0cc8c55-6d07-498c-9503-21aae47a2607.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDI3OTksIm5iZiI6MTczMjAwMjQ5OSwicGF0aCI6Ii8xNTU0NTcyMzcvMzg3MzYzMDUxLWQwY2M4YzU1LTZkMDctNDk4Yy05NTAzLTIxYWFlNDdhMjYwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQwNzQ4MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjA2ZTY0MjM0ZjJmYjI5NjQ1ODIyZGE2NDQ5YWE4MmNiNzk0OWVlMzIzYjZhMDFhZDQ5OTNhYzI4OTUzODcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.r_vqqBY7iVqAlo_-e6RcLY8i5w9r0Yuk5ATvjA1FUu8)
> 
> > 无缩略图以及目前的播放时长
> > ![image](https://private-user-images.githubusercontent.com/155457237/387363462-071f6a3c-3e33-45e3-b961-7a07d57476fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDI3OTksIm5iZiI6MTczMjAwMjQ5OSwicGF0aCI6Ii8xNTU0NTcyMzcvMzg3MzYzNDYyLTA3MWY2YTNjLTNlMzMtNDVlMy1iOTYxLTdhMDdkNTc0NzZmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQwNzQ4MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTZjYjU4ZjBlYjMzMTY4NWY2ODJjYWY2OTMzOTM1MjhlOTE0YzgyYWI3NDVkYjZkZTAwNTk1Yjc5NDE0YzY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Fxof47gp_OsvN0b04XQei8-zAU-Wko6fAkhWWiEOUuA)
> 
> > 退出后会直接显示已播放
> > ![image](https://private-user-images.githubusercontent.com/155457237/387363584-1056599e-424e-45ea-8ece-b5596c591634.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDI3OTksIm5iZiI6MTczMjAwMjQ5OSwicGF0aCI6Ii8xNTU0NTcyMzcvMzg3MzYzNTg0LTEwNTY1OTllLTQyNGUtNDVlYS04ZWNlLWI1NTk2YzU5MTYzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQwNzQ4MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTA0N2E1YmE1MGJkN2M1ODU4ZTg0NzBlMTZhZDUxNTU1N2M2ODRjOGIwN2UxMWU1NWRmMGRjNDYzZWQ4M2ZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Y3B9-LlqcK2OQEI8HjasrF-Mv1RP4Hv5cyo8CR5uF2c)
> 
> > 这个是等待媒体信息出来后再扫章节图缩略图就正常，而且正常和不正常的进度条颜色也不同
> > ![image](https://private-user-images.githubusercontent.com/155457237/387364005-0e93f175-432f-4df7-82f0-de1ec3062a76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDI3OTksIm5iZiI6MTczMjAwMjQ5OSwicGF0aCI6Ii8xNTU0NTcyMzcvMzg3MzY0MDA1LTBlOTNmMTc1LTQzMmYtNGRmNy04MmYwLWRlMWVjMzA2MmE3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQwNzQ4MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzBlZGE5MjAxNDA1Yzk1OGM0NDI3MGVjNTIxZDVmNGVkMWMxMTE2OTY4ZjU3YTIyMzI1NTcwOWY4Y2I3ZTlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.opCfcD4MrywTuTYIbf4mPToYFUL6NREORgX2q4S0HYI)
> 
> 还有媒体信息提取那里的媒体库范围，留空包含所有。 但我这里实际情况并没有留空包含所有，需要手动指定库，不然媒体信息提取还需要增加一个计划任务，并把片头和缩略图章节图 添加媒体时提取关闭 手动开启计划任务。



> > 补充一下
 神医，我忘说了我是4.9.0.30版本，可能是测试版的问题？
 神医，晚点回家后我看能不能上传一个视频，我这里是稳定触发的。
 
> > 第一个问题
> > 神医，多线程入库会先出来元数据，媒体信息要稍等一下才能出来，就在没出来的那个时间内开启扫描缩略图章节图或者片头就会出问题。
> > 导致无论播放多长时间退出后都会直接显示已播放和emby里已经扫好但出不来缩略图。
> > 具体原因我也弄不太清楚，我这触发都是在媒体信息没出来的那段时间 扫描章节图缩略图或者片头就会出事。
> > 我这里媒体信息没出来前可以开启扫描章节图缩略图或者片头的计划任务的。
> 
> > 第二个问题
> > 神医，我这触发这个问题后是删掉后重启emby再重新入库保证媒体信息出来前不要扫章节图缩略图和片头。
> 
> > 第三个问题
> > 文件夹内thumb打开正常，bif我之前提过来过几个图片也正常的 ，数据库里的章节标记我确实还没看。
> > 就是在emby里播放进度那里不显示缩略图和无论播放多长时间退出后都会直接显示已播放
> 
> > 第四个问题
> > 这个是个另外的问题，不好意思神医，我这个我回去再看一下。
> > 我记得之前留空出不来媒体信息，需要再开个计划任务



> > 补充一下
> > 神医，我忘说了我是4.9.0.30版本，可能是测试版的问题？
> > 神医，晚点回家后我看能不能上传一个视频，我这里是稳定触发的。
> 
> > 第一个问题
> > 神医，多线程入库会先出来元数据，媒体信息要稍等一下才能出来，就在没出来的那个时间内开启扫描缩略图章节图或者片头就会出问题。
> > 导致无论播放多长时间退出后都会直接显示已播放和emby里已经扫好但出不来缩略图。
> > 具体原因我也弄不太清楚，我这触发都是在媒体信息没出来的那段时间 扫描章节图缩略图或者片头就会出事。
> > 我这里媒体信息没出来前可以开启扫描章节图缩略图或者片头的计划任务的。
> 
> > 第二个问题
> > 神医，我这触发这个问题后是删掉后重启emby再重新入库保证媒体信息出来前不要扫章节图缩略图和片头。
> 
> > 第三个问题
> > 文件夹内thumb打开正常，bif我之前提过来过几个图片也正常的 ，数据库里的章节标记我确实还没看。
> > 就是在emby里播放进度那里不显示缩略图和无论播放多长时间退出后都会直接显示已播放
> 
> > 第四个问题
> > 这个是个另外的问题，不好意思神医，我这个我回去再看一下。
> > 我记得之前留空出不来媒体信息，需要再开个计划任务

**Comment by sjtuross** [comment]
一个issue就讨论一个问题，否则太混乱了。我今天测试的时候就是4.9.0.30，应该不是测试版的问题。

没有媒体信息，那么播放就没有进度，经此而已，为什么要跟章节关联起来？thumb这类元数据图片跟播放是否显示章节缩略图也是不相关的。

关于没有媒体信息能扫章节这件事，你要么建个测试库，提供复现步骤

**Comment by entaroartanis114514** [comment]
神医，我现在也弄不懂具体原因了，电影也偶尔会这样，但媒体信息也是出来了的
https://drive.google.com/file/d/1-gyBspaO7Hqcy2zIV3dOgJVnEQztTWL4/view?usp=sharing

**Comment by sjtuross** [comment]
我看你目录里是mkv，那就是直连的库，不是strm，按你最一开始提到的插件配置，那就是开了追根模式+独占模式，通过这种方式提取媒体信息的？

有问题的视频貌似有个特征，没有时长和大小显示，比如下面就有，你看看是不是这样？然后重新入库，先扫出媒体信息，再看下什么情况？

![image](https://github.com/user-attachments/assets/554d17f7-31d7-42a0-a450-1dd3136f51b5)
![image](https://github.com/user-attachments/assets/6c9a1c21-5c21-468f-a6d9-c32820b9a1f6)

**Comment by entaroartanis114514** [comment]
还真是，但凡是这种有问题的都没有时长和大小显示。
![image](https://github.com/user-attachments/assets/f041d4a7-c5ff-4fca-bd26-1d789aac40e6)
![image](https://github.com/user-attachments/assets/d17a61ba-42d4-47c6-b6cd-ae2f238b49aa)
家里人在看电视剧，我现在重开不了....这个是昨天的重新入库后，时长和大小显示就都有了，也正常了。
![image](https://github.com/user-attachments/assets/f27ece64-2889-45b6-9573-542a08fa0916)
![image](https://github.com/user-attachments/assets/7045ab45-f3d0-42ae-ba88-c33b8c50d14f)
神医，这种情况是提取章节图导致提取媒体信息的任务停了吗？

**Comment by sjtuross** [comment]
> 这种情况是提取章节图导致提取媒体信息的任务停了吗？

现在不好说，你先重新入次库，看看能否扫出时长和大小，排除视频本身的问题。

如果视频本身没问题，那么需要你开调试日志，复现一次后发我，把相关的片名告诉我，我看了日志再说。

**Comment by entaroartanis114514** [comment]
神医，明天白天我看看有没有时间弄吧，这玩意太抽象了，一直删不干净，有的时间和大小一开始能看见  刷新一下就没了，有的之前出不来，这次出来了。这个咒术回战太抽象了
![image](https://github.com/user-attachments/assets/876549dd-c5c2-4748-a9d3-6228aa9143e0)
![image](https://github.com/user-attachments/assets/16e44b09-c76d-4efd-b858-fc249ab7a6b9)

**Comment by entaroartanis114514** [comment]
删了半天，选择重新匹配然后刮削一下就全出来了...
还是使用的咒术回战第一季，复现后我点击重新手动识别刮削了一下让大小和时间出来了
我选择的是这个4:05的日志 ，事先重启1.5MB差不多，日志时间应该是默认的UTC时间...
![image](https://github.com/user-attachments/assets/fa2c00f2-d4cf-458d-a41f-df6fe28214f8)
[embyserver.txt](https://github.com/user-attachments/files/17836201/embyserver.txt)

**Comment by entaroartanis114514** [comment]
神医，不是库的问题，这是重开了个库。仍然会有这种东西，之前的库已经是重开过两次了，都是因为那种东西。因为之前不懂那个是什么原因，现在的话是不太可能一个个去看时长和大小，太多了...
新开的库只加了这些和咒术回战，咒术回战确实正常了，但是我觉得已经出现这种东西就没必要全加再测一遍了吧？
![image](https://github.com/user-attachments/assets/4a5f8ea4-a874-4c04-8b8c-451342e9874e)
![image](https://github.com/user-attachments/assets/41a6b5a4-d6d6-4c15-9383-6cfd7d3b1eef)
![image](https://github.com/user-attachments/assets/d08ee083-62be-4724-9f3e-5b1812c94afc)

**Comment by entaroartanis114514** [comment]
神医，这是在上面之后又开了个库，中间我按了几次提取缩略图，其它仍然是没做其它任何操作，甚至都只留了神医插件和emby自带的插件。
仍然可以复现，就不截那么多图了。
出现原因目前基本都是入库时提取缩略图导致的，但是手动识别刮削时我再手动运行提取缩略图任务却可以正常获取时长和大小
![image](https://github.com/user-attachments/assets/9ddb1fe4-0164-4ca4-b84a-50ef8d4749ef)
![image](https://github.com/user-attachments/assets/484d03b4-bf94-448d-80ee-cd809f217756)
![image](https://github.com/user-attachments/assets/9bbb1304-6a87-4453-9540-ff4e53388340)
![image](https://github.com/user-attachments/assets/ae29e5e0-d5b7-43fa-8f50-25b6bc394218)

**Comment by sjtuross** [comment]
我想知道的是单纯10线程跑提取媒体信息的结果，不同时跑章节和片头。

**Comment by entaroartanis114514** [comment]
神医，不跑片头和章节是正常的。
不是影片问题，一跑片头和章节不止这个影片其它的也会出现问题。如果不跑就正常入库
我先往谷歌上传四集,因为我这里上传速度有些慢。
要等些时间了,上传完我再发出来
![image](https://github.com/user-attachments/assets/6ba76ca3-f6f6-4c81-99ca-dfe89e7e71ce)
![image](https://github.com/user-attachments/assets/f236446e-2c87-47c4-a80b-d372c3429705)

**Comment by sjtuross** [comment]
好的，问题我基本上清楚了，先看看能不能找到根本原因吧。用你的片子，回头在我这边尝试复现一下。

**Comment by sjtuross** [comment]
跟你插件选项配置一样，10线程，媒体库开了章节和片头“作为计划任务及添加媒体时”

1. 不开追更模式，运行计划任务提取媒体信息，然后我手工启动扫章节，要连续点几次才行，因为一开始都没有媒体信息不在范围内。12个视频媒体信息扫完了，章节就出了一个BIF并且任务结束了，因为启动时估计只有一集有媒体信息，其他都不在范围内。查看所有12集都有大小和时长。
2. 开追更模式，扫库入库，12集媒体信息都完成了，发现无论章节和片头任务都没有自动启动，查看所有12集都有大小和时长。

我反复试了好几次都没能复现你说的问题。测试环境用的是今天Emby最新的测试版4.9.0.32，插件是最新的42预览版 https://github.com/sjtuross/StrmAssistant/releases/tag/v1.0.0.42 扫章节错误被记录数据库已经被屏蔽掉了，还有些其他优化，你要么再试试看。

**Comment by entaroartanis114514** [comment]
神医，我也升级了4.9.0.32，插件也更新到最新版本了。
目前我测了两个动漫37集和两个电影,现在没出什么问题，时长和大小都正常。
今天太晚了...我明天再测几个看看

**Comment by entaroartanis114514** [comment]
神医，我在上面那个回复之后又加了100集动漫，大概看了看都是有时长和大小。
电影在之后加了五部，仍然有两部又出问题了。而这两部我用新的测试库是没问题的，时长大小正常。也应该不是视频的问题，只是两个库一个4.9.0.32，一个4.9.0.30
> 在更新最新版本后总共剧集加了150集左右我看着没什么问题，电影添加了七部  发现两部有问题。
都是开启入库提取缩略图，还有入库时我再手点提取缩略图。扫描片头也有开每15分钟运行的计时任务。
![image](https://github.com/user-attachments/assets/c3536f9d-71ca-4567-8a67-88d297d57ab5)
![image](https://github.com/user-attachments/assets/b5114d37-6b51-49ea-91c5-6e51961104f2)
![image](https://github.com/user-attachments/assets/9361d9ed-e26e-42f2-a1a6-ce25f0851b5b)
![image](https://github.com/user-attachments/assets/df1bf374-536e-4598-a768-93ab442a462f)

**Comment by sjtuross** [comment]
插件42版修复过追更模式中一个线程安全的问题，现在回想跟你提的这个问题应该有点关系。虽然很遗憾还有发生，但应该会有改善。

线程安全类的问题会造成类似这种奇怪的现象，很难稳定复现，我都没能复现。

你说手动刮削也发生了，那就更奇怪了，这个操作应该跟插件没关系。

**Comment by entaroartanis114514** [comment]
神医，关于手动刮削，我的意思其实是之前如果出现这种没时长和大小，手动识别刮削后即可获取到时长和大小。
现在我手动识别刮削也获取不到了，删除后重新入库才可以获取到了。
这个问题太抽象了，但确实已经比之前好很多了

**Comment by entaroartanis114514** [comment]
神医，现在复现条件我也弄不太清楚了..更新版本后我这里基本不怎么会出现，之前的触发条件也出不来了。
在上面那条回复后我加了大概200集剧集，12部电影。
还是只有两部电影出问题，但那会没开调试我也弄不太清楚具体原因。
我看群里是说同时入库多个剧集，我晚上再试一下如何触发，以及看关闭拼音排序能不能解决

**Comment by entaroartanis114514** [comment]
神医，我同时入库61部剧集和5部电影后又出现了一部，我觉得和群里的不太一样。
媒体信息持久化打开后json在电影目录也有生成，而且里面有记录时长和大小。
时长和大小也正确，但不在emby那里显示时长和大小，还有一个地方就是他的类标题仍然是铁血战士，而不是拼音。
之前更新后的四部没注意这个类标题是否是拼音,不太记得了....
神医，我明天再入多点看下这种没时长和大小共同的特征是什么
[铁血战士 (2018) - 1080p - BluRay - X264 - DTS - CMCT-mediainfo.json](https://github.com/user-attachments/files/17969650/2018.-.1080p.-.BluRay.-.X264.-.DTS.-.CMCT-mediainfo.json)

**Comment by sjtuross** [comment]
这个现象我知道，json中又大小和时长，但Emby里没有，基本上确定是拼音首字母这个功能造成的，多线程下它有可能保存了一个刷新前的不完整对象。我已经重新实现了，只改逻辑不保存，下个版本希望可以解决了。

**Comment by sjtuross** [comment]
这次改动比较多，还有待测试，也不排除Emby内部存在线程安全的问题，毕竟它不是按照多线程设计的。你确认下有问题的视频有没有对应的json生成以及大小和时长，可能可以利用这个来做补救措施。

**Comment by entaroartanis114514** [comment]
神医,有问题的视频的json都是有时长和大小的。
我有时间测试一下是几部开始出问题的，今天刚刚把昨天有问题的四部删除重新后同时入库，出现一部出问题，json正常，再次删除后单独重新入库这一部emby正常显示大小和时间。

关于配置和环境
我是群辉7.2版本的docker，i5 8400T、48G DDR4 3200内存、机械本地盘。
其实我感觉docker版本会慢很多,我也不大清楚是不是群辉的问题,没太用过其它正经的linux比较，windows我之前试过几次不用神医插件都扫的特别快，docker用了神医插件才勉强能靠近windows的效果。

**Comment by sjtuross** [comment]
45版我更新了一下，独占模式下扫库，如果发现有媒体信息但无大小和时长，会尝试用json来修复

**Comment by entaroartanis114514** [comment]
神医,应该算是好了？
第一次先入了六部没问题，然后第二次入了11部。
只有第二次入库11部电影时媒体信息和json等了几分钟一直出不来，我看了下日志那会是有信息，但是没出来，可能是那会在扫缩略图？
关闭缩略图任务然后手动提取媒体信息全部都有时长和大小了。
第三次后面又测试删除八部电影外重新硬链接入库和新增一部电影，总共九部都正常。

**Comment by entaroartanis114514** [comment]
神医，我重开了个库，只加了电影大概550部这样,然后随机抽了五分之一没发现。
剧集就没试了，之前更新后一直没发现问题。
实在抽不动了,上面测试一波下面又抽五分之一看。
问题应该是已经解决了。
