### ISSUE TITLE
大佬，能编译一个arm64（armv8）架构的版本么

### ISSUE THREAD

**Issue by guowanghushifu** [sjtuross/StrmAssistant#34]
大佬，能编译一个arm64（armv8）架构的版本么

release里面的dll应该是x64的？ 求解答，谢谢。

**Comment by sjtuross** [comment]
dll是全平台的，魔改功能暂时不支持arm平台，https://github.com/sjtuross/StrmAssistant/issues/8#issuecomment-2435407002
