### ISSUE TITLE
自动生成缩略图问题

### ISSUE THREAD

**Issue by gldl137** [sjtuross/StrmAssistant#35]
是不被mp整理过来的文件，不能自动生成缩略图，必须手动计划任务才能出现。
![QQ拼音截图20241127213250](https://github.com/user-attachments/assets/ac0a16f6-3777-43e1-a103-6a40b274e215)
![QQ拼音截图20241127213335](https://github.com/user-attachments/assets/e3da2955-a79a-4ee0-83df-e33f16f0acb1)

**Comment by sjtuross** [comment]
这个你要从Emby历史日志里找到这一集，首先看助手有没有派发任务（就是Strm Assistant为关键字的一条日志），然后再找接下来的错误日志，才能知道原因。

大概率是因为60秒超时，Emby就放弃了，计划任务那里我是做了单任务魔改超时，用线程数乘以60秒，追更模式没做主要是避免长时间卡入库的待处理的媒体。

**Comment by sjtuross** [comment]
这几个失败的都有这个错`output file not found`，意思就是尝试去截图了，但没能得到图片的输出结果。一种可能是视频编码参数不标准，Emby自带的ffmpeg截不出来，另外一种可能是alist直链下载过程不稳定，有中断。

你可以建个测试的本地库，下载E07到本地，如果也截不出来，那就是第一种可能，只能换片源，或者用其他工具截。

从插件的角度，已经正常派发任务了，至于能不能出结果还是看Emby和外部因素。

**Comment by gldl137** [comment]
尝试了几次，有时候截图出来，有时候截不出来，感觉是网盘直连不稳定，

**Comment by gldl137** [comment]
最后我总结下，阿里的网盘截图成功率不高，115的网盘基本都能成功，下载的原始文件截图都能成功，如果直接在emby里面播放流畅的截图就没问题。阿里起播速度慢和拖动卡顿，都会导致截图失败
