### ISSUE TITLE
自动更新到1.0.0.44版本，很多功能无法用

### ISSUE THREAD

**Issue by EndBoy520** [sjtuross/StrmAssistant#38]
![屏幕截图 2024-12-03 111545](https://github.com/user-attachments/assets/f8013451-4fb3-463a-ab69-f1a7b0b1e0f1)
之前安装的时候插件功能时可以选中，现在不知道怎么变灰了，无法选中。只有白色框可以选，偏灰色的无法选。

Emby版本：[4.8.10.0] arm64 deb版
另外：我想问一下，功能里面的JSON文件的媒体信息持久化与Tmm刮削生成的xml的媒体信息有啥区别？Emby里面还有个Xml Metadata这个插件，安装过后媒体库的元数据读取器就会有Emby xml这个选项，这个是能读取tmm生成的xml版媒体信息么？我在tmm设置了保存xml的媒体信息

没太搞明白，之间关联。

**Comment by sjtuross** [comment]
魔改功能暂时不支持arm，我这里解释过 https://github.com/sjtuross/StrmAssistant/issues/8#issuecomment-2435407002

json持久化跟tmm那个xml的作用类似，但我的json里面还有章节片头片尾标记信息，这是tmm的xml不能提供的。考虑过跟tmm兼容，但并不是人人都用tmm并且持久化媒体信息至xml，而且tmm的xml读取写入代码是apache license，不想跟他扯上任何关系。Emby那个Xml Metadata插件，看名字就是元数据相关的，跟媒体信息完全不相干。
