### ISSUE TITLE
用标题自动补全的标题 无法手动修改 被强制了

### ISSUE THREAD

**Issue by wc906398139** [sjtuross/StrmAssistant#39]

**Comment by sjtuross** [comment]
无法复现

**Comment by wc906398139** [comment]
> 无法复现

关闭元数据刮削，用插件，你可以看看 命名是手动修正不了的

**Comment by sjtuross** [comment]
我当然是修改成功了才这么说的

**Comment by wc906398139** [comment]
这是tmdb 无数据视频文件
关闭自动补全标题 能正常显示
打开自动补全标题 显示不正常
![11截图_2024-12-04_21-36-00](https://github.com/user-attachments/assets/c308aa5f-1084-4e62-ac1e-1767214b02bd)
![11截图_2024-12-04_21-36-33](https://github.com/user-attachments/assets/2e212ee9-4d76-4023-856a-e84eeb817517)

**Comment by sjtuross** [comment]
你得挑几集元数据打包发我，视频用空的strm文件代替，我要能复现才行。显示问题跟你说的无法修改有什么关联？你提供的信息只是结果，但不足以复现问题。

**Comment by wc906398139** [comment]
> 你得挑几集元数据打包发我，视频用空的strm文件代替，我要能复现才行。显示问题跟你说的无法修改有什么关联？你提供的信息只是结果，但不足以复现问题。

这几个文件没用 元数据，本地文件名显示的，但是用插件就会被强制被改成这个问题，关闭功能能显示文件名，打开变第 集，打开后然后名字也无法编辑保存。
![image](https://github.com/user-attachments/assets/7114f9fb-23ab-473c-9d26-920be1cb2f2e)
![image](https://github.com/user-attachments/assets/24ffc5ed-207b-469e-b752-40a3ef90e559)

**Comment by sjtuross** [comment]
试试这个版本 https://github.com/sjtuross/StrmAssistant/actions/runs/12183326849

**Comment by wc906398139** [comment]
> 试试这个版本 https://github.com/sjtuross/StrmAssistant/actions/runs/12183326849

正常了
