### ISSUE TITLE
阿里云盘限速是否可以通过增加emby请求线程解决

### ISSUE THREAD

**Issue by ppamoy** [sjtuross/StrmAssistant#4]
阿里云盘限速是否可以通过增加emby请求线程解决？
阿里云盘目前限速500k，播放不流畅。如果是用多线程下载器，如idm或者aria2，可以单文件2m/s的速度。
是否可能增加emby请求strm文件的线程数来解决这个问题

**Comment by sjtuross** [comment]
限速500k是非会员账号？跟播放器有没有关系？我得先能够复现。动态魔改只能随缘，需要做大量逆向研究，除非已经有方案可以参考实现。
