### ISSUE TITLE
人员增强TMDB问题

### ISSUE THREAD

**Issue by wc906398139** [sjtuross/StrmAssistant#40]
好像就处理了，季度人员问题，并没有处理特别篇的人员问题。
如果剧集只有一个季度和特别篇，那么原本emby演员只会下载出现集数最多的演员。
比如：https://www.themoviedb.org/tv/45213-usagi-drop
![11截图_2024-12-04_19-21-21](https://github.com/user-attachments/assets/b15ad0fb-c3fd-4c14-939d-ebf9dab3faa5)
![11截图_2024-12-04_19-21-52](https://github.com/user-attachments/assets/5b2e9615-d5cf-45ce-9160-a21ebdc86b12)

**Comment by sjtuross** [comment]
特别篇被我过滤掉了，有的节目可能有几十集特别篇，有的可能是嘉宾，列为节目的主要人员可能不太合适

**Comment by wc906398139** [comment]
> 特别篇被我过滤掉了，有的节目可能有几十集特别篇，有的可能是嘉宾，列为节目的主要人员可能不太合适

对于动漫的话很糟糕。

**Comment by sjtuross** [comment]
看了下白兔糖特别篇tmdb api的返回数据，演员是空的，想做也做不了。

https://api.themoviedb.org/3/tv/45213/season/0?api_key=f6bd687ffa63cd282b6ff2c6877f2669&append_to_response=images,keywords,external_ids,credits,videos

![image](https://github.com/user-attachments/assets/93e9b405-2465-4994-828a-c37cfaca13be)

**Comment by wc906398139** [comment]
> 看了下白兔糖特别篇tmdb api的返回数据，演员是空的，想做也做不了。网站估计是把所有集的演员汇总了。
> 
> https://api.themoviedb.org/3/tv/45213/season/0?api_key=f6bd687ffa63cd282b6ff2c6877f2669&append_to_response=images,keywords,external_ids,credits,videos
> 
> ![image](https://private-user-images.githubusercontent.com/940110/392390094-93e9b405-2465-4994-828a-c37cfaca13be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMTk4MTQsIm5iZiI6MTczMzMxOTUxNCwicGF0aCI6Ii85NDAxMTAvMzkyMzkwMDk0LTkzZTliNDA1LTI0NjUtNDk5NC04MjhhLWMzN2NmYWNhMTNiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQxMzM4MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODZlNTM1N2UwOGRmOGQ3ZDI2NGFkZDRhMTUxNjI2OTNjYzM1NjFkZTUzZTQ2NWI1Mjc5MjJjZDg4N2MxY2Y1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GQ6450vgWUTy0KIA57l8YroaVpTLK0JBM7CiCoXTrPI)

这类情况 都是一样的么？api返回都是空的
https://www.themoviedb.org/tv/83099

**Comment by sjtuross** [comment]
在tmdb api节目系列返回的演员不全的情况下，只能通过合并各季或各集的演员来弥补。我现在采用的是合并各季，但tmdb网站到底是什么逻辑不得而知。如果合并各集，那么这个数据量和处理量会大不少，因为每集的元数据刷新都要重新计算。

归根到底是tmdb api的问题，插件只能尽可能改善，但要完美看来不太现实。

**Comment by wc906398139** [comment]
> 也是空的，特别篇估计都是空的，其实也有一定道理。
> 
> 在tmdb api节目系列返回的演员不全的情况下，只能通过合并各季或各集的演员来弥补。我现在采用的是合并各季，但tmdb网站到底是什么逻辑不得而知。如果合并各集，那么这个数据量和处理量会大不少，因为每集的元数据刷新都要重新计算。
> 
> 归根到底是tmdb api的问题，插件只能尽可能改善，但要完美看来不太现实。

了解了，感谢。
