### ISSUE TITLE
独占模式开启后刷新元数据时依然会提取媒体信息

### ISSUE THREAD

**Issue by leftcausedit** [sjtuross/StrmAssistant#41]
独占模式打开后，Emby入库时会自动禁用ffprobe和ffmpeg；但是刷新元数据和手动或刮削时不会禁用ffprobe，还是会extract mediainfo
emby 版本: 4.9.0.32
strmassistant 版本: 1.0.0.45

**Comment by sjtuross** [comment]
设计是这样的，wiki里也写了规则，为了保留强制刷新媒体信息的手段。

**Comment by leftcausedit** [comment]
![image](https://github.com/user-attachments/assets/63933fd4-8311-4c2f-b399-bd86dd2529e4)
跟wiki说的不一样

**Comment by sjtuross** [comment]
这是简介，你要看具体规则说明

**Comment by sjtuross** [comment]
手动匹配的内部操作相当于选了替换所有图片的刷新。如果不放行，万一元数据那边没有截图，就没法视频截图了，结果就没图了。不想破坏直连的这个特性。这个wiki里没写，因为过于复杂，而且是最为强制刷新的手段。

**Comment by leftcausedit** [comment]
刚刚找到规则，按照上面说的，第一次入库会禁用ffprobe，第一次刷新元数据不会禁用ffprobe，后续刷新元数据（文件不变）会禁用ffprobe。
1.能不能加一个开关，刷新元数据一刀切禁用ffprobe呢，有些入库没有自动识别，要手动识别的时候，要扫半天；
2.我刚刚尝试的时候，一个电影后续添加不同版本（比如不同分辨率的文件）的时候，他是会调用ffprobe的；

**Comment by leftcausedit** [comment]
> 手动匹配的内部操作相当于选了替换所有图片的刷新。如果不放行，万一元数据那边没有截图，就没法视频截图了，结果就没图了。不想破坏直连的这个特性。这个wiki里没写，因为过于复杂，而且是最为强制刷新的手段。

对的，所以我把提取缩略图都关掉了，就是在扫的过程中尽量不对挂载的盘进行请求；
我的意思是有这样的开关可以实现emby除了播放之外完全不从挂载盘中读取任何媒体内容，只读取文件列表。
关闭这个开关，刷新元数据可以调用ffporbe；打开这个开关，刷新元数据不调用ffprobe。这样比较灵活一点

**Comment by sjtuross** [comment]
现在能识别手动匹配，然后屏蔽，你可以试下最新的编译版 https://github.com/sjtuross/StrmAssistant/actions/runs/12211131011 其他改动暂时不考虑了，如果要完全不从网盘读媒体，可以考虑用strm方案。
