### ISSUE TITLE
不是同一时间入库的电影不能自动合并

### ISSUE THREAD

**Issue by GGbond1680** [sjtuross/StrmAssistant#42]
<img width="558" alt="image" src="https://github.com/user-attachments/assets/b97e18ef-9799-446b-a62a-a79656b9bef6">
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/f0898a64-c785-45a6-9d76-1939a0102519">
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/bd8d0e77-bc41-48c5-9a96-a2e5cf1c00b3">
神医，不是同一时间入库的电影并没有合并起来，看路径都是在同一个目录下

**Comment by sjtuross** [comment]
有没有可能之前的合并是其他插件或脚本或手工做的？你浏览器F12里看一下已经合并的那个的PresentationUniqueKey是什么，最后有没有下划线

类似这样的请求 http://localhost:8096/emby/Users/c745628408104696b542cc67690bb4cb/Items/38769?fields=ShareLevel&ExcludeFields=VideoChapters%2CVideoMediaSources%2CMediaStreams&X-Emby-Client=Emby+Web&X-Emby-Device-Name=Firefox+Windows&X-Emby-Device-Id=b638940c-8734-46b1-b821-d8e3057d2619&X-Emby-Client-Version=4.9.0.32&X-Emby-Token=f38fe0ed6bad4126abf46a1dc63d4666&X-Emby-Language=zh-cn

![image](https://github.com/user-attachments/assets/c63cdadc-2b01-4118-9d1c-a4b46d6cd0f3)

**Comment by GGbond1680** [comment]
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/fa9725a6-3c0e-4389-b351-42b8ded0a669">
这个吗，有下划线。我的合并一直都用的你的脚本，应该是没用过其他的，再发现不合并后，我才有用过as群主红尘的合并脚本手动合并过一次

**Comment by sjtuross** [comment]
用户单独合并或分离的，Emby会加下划线，就不会再参与到扫库后的自动合并，否则就可能覆盖了用户的行为。

那个单个的天气之子你看看有没有下划线，如果没有，那么可以试试把现在那个已经合并的重新入库，看下结果。

**Comment by GGbond1680** [comment]
感谢神医 确实是这个原因
