### ISSUE TITLE
部分选项无法开启

### ISSUE THREAD

**Issue by RogerProSelf** [sjtuross/StrmAssistant#43]
首先感谢大佬开发的插件！

注意到很多选项无法启用，比如“拼音首字母排序”和“强制媒体库排序”等，不确定是否是因为部署在ARM架构的原因？

如果是的话，是否有支持的计划呢？

再次感谢！

**Comment by sjtuross** [comment]
你猜对了，我在这里解释过 https://github.com/sjtuross/StrmAssistant/issues/8#issuecomment-2435407002

只要上游解决，插件立刻马上就能支持arm。我知道有些老外野路子的fork搞定了Android，但我暂时有限的时间都在插件功能上，没时间研究底层的东西，希望还是有的，但可遇不可期。
