### ISSUE TITLE
能否实现以原产地语言获取封面

### ISSUE THREAD

**Issue by ironstress** [sjtuross/StrmAssistant#44]
如今很多国内引进的电影，封面会加上很多宣传语，像牛皮癣一样，不好看

在tmdb里是有“原电影语言”属性的

举例正在上映的“角斗士2”
![image](https://github.com/user-attachments/assets/118ca805-9fa3-4992-811e-e0d4c37d567f)
![image](https://github.com/user-attachments/assets/1cd91db3-9639-44c0-960f-dfd646c3f438)

**Comment by sjtuross** [comment]
这不是已经实现了嘛，原语言海报 https://github.com/sjtuross/StrmAssistant/wiki/原语言海报--(Original-Poster)

**Comment by ironstress** [comment]
> 这不是已经实现了嘛，原语言海报 [https://github.com/sjtuross/StrmAssistant/wiki/原语言海报--(Original-Poster)](https://github.com/sjtuross/StrmAssistant/wiki/%E5%8E%9F%E8%AF%AD%E8%A8%80%E6%B5%B7%E6%8A%A5--(Original-Poster))

奇怪，原来我早就开启了，可11月30日入库的电影还是获取的汉语海报

**Comment by sjtuross** [comment]
媒体库海报语言要留空才行，之前做过一个优先级的改动，wiki也有写。
