### ISSUE TITLE
搜索是否能添加季名

### ISSUE THREAD

**Issue by jorejia** [sjtuross/StrmAssistant#45]
现在Emby支持刮削季名了，搜索也能支持就更好了

**Comment by sjtuross** [comment]
加了季标题搜索范围选项了，可以试试预览版 https://github.com/sjtuross/StrmAssistant/releases/tag/v1.0.0.47

**Comment by wc906398139** [comment]
> 加了季标题搜索范围选项了，可以试试action编译版 https://github.com/sjtuross/StrmAssistant/actions/runs/12299776310

好像没效果

**Comment by sjtuross** [comment]
最新47版已支持
