### ISSUE TITLE
魔改刮削，刮削主题曲

### ISSUE THREAD

**Issue by LINKlang** [sjtuross/StrmAssistant#47]
能否修改 emby 的刮削机制，像 tmm 一样允许刮削 theme.mp3

**Comment by sjtuross** [comment]
Emby插件商店里已经有`Movie Theme Songs`和`TV Theme Songs`这两个插件了，虽然要花点小钱，也可以打包买。所以我觉得没必要再重复造轮子了。

**Comment by LINKlang** [comment]
主要是看您这边，如果觉得没必要的话可以close这个issue
