### ISSUE TITLE
关于动漫的季的封面图以及缩略图

### ISSUE THREAD

**Issue by AAZhe1997** [sjtuross/StrmAssistant#50]
已经勾选原语言海报，首选图像下载语言也留空。
可是我发现季的封面图以及缩略图貌似没法实现源语言，是这个选项不支持季的封面图以及缩略图吗？
![image](https://github.com/user-attachments/assets/d3d1a7f1-2bfc-4281-b285-228877e1a891)
![image](https://github.com/user-attachments/assets/4dd3a260-5c27-45f1-bb19-b4af1c968211)

**Comment by sjtuross** [comment]
感谢反馈，这是一个bug

除了主海报，其他是非完美支持，因为Emby的内存对象上没有原语言或国家的字段，只能基于节目系列的原标题判断中日韩英来选择海报，绝大部分情况是ok的，但是正则有bug，等下个版本。

我本机修复后是这样的

![image](https://github.com/user-attachments/assets/fa645a2b-d0b7-4683-a2ed-7cab08655b25)

**Comment by sjtuross** [comment]
https://github.com/sjtuross/StrmAssistant/releases/tag/v2.0.0.0

**Comment by AAZhe1997** [comment]
我还想问一下，这个集的图像是否支持呢？
![image](https://github.com/user-attachments/assets/ed354abb-34ec-4a6b-b24c-b60f0ea8bcdc)
刷新元数据后图片好像还是以中文为主
![image](https://github.com/user-attachments/assets/c6f75409-da41-4065-a303-38eaf0bee16a)
这集是可以搜到日语图片的
