### ISSUE TITLE
请问片头片尾这些章节信息可以备份吗

### ISSUE THREAD

**Issue by suraxiuxiu** [sjtuross/StrmAssistant#51]
emby的数据库坏过一次，重新入库后，那扫描片头耗时堪称恐怖。
有没有办法备份这些片头数据，比如写入元数据里。
emby有个插件是干这个事情的，说是按但是效果有点差强人意。试过备份然后新建个emby来恢复备份，结果片头全是乱的

**Comment by sjtuross** [comment]
https://github.com/sjtuross/StrmAssistant/wiki/媒体信息持久化-(MediaInfo-Persist)

媒体信息json文件同时包含章节片头等信息，可一并恢复。

**Comment by suraxiuxiu** [comment]
大佬牛逼

**Comment by suraxiuxiu** [comment]
顺便问一下  有的剧集片头信息不正确，或者直接不生成片头。
用Chapter API删除章节信息重新运行生成，看日志已经提取音频指纹去识别了，但片头还是不正确或者没有。
这种情况要怎么办呀

**Comment by sjtuross** [comment]
不正确那是原生算法决定的，重复跑结果也是一样的。原生的片头不是保证一定会有的，如果计算出的可信度为0就没有，属于正常情况，可以去日志里面找这一集的Confidence信息。有时集数太少也会出现这个情况，后续集进来后可能都会出来。

另外，插件提供基于行为的探测，可以播放时通过暂停手动修正，作为辅助搭配使用，具体看Wiki
