### ISSUE TITLE
请求修复群晖套件emby错误，可以把临时tmp文件设置到 /config 内吗？

### ISSUE THREAD

**Issue by kanmanli** [sjtuross/StrmAssistant#6]
在已知问题里，群晖emby套件无法使用中文搜索，原因是dsm7不允许/tmp目录执行文件，所以可以把临时tmp文件设置到 /config。
目前emby套件的临时解决方法是，使用命令行sudo mount -o remount,exec /tmp，临时移除群晖对/tmp的 noexec属性，但是系统重启会失效，恢复系统默认的命令行sudo mount -o remount,noexec /tmp

**Comment by sjtuross** [comment]
你是说遇到了类似下面的错误？这不是插件可以控制的，这是魔改框架在linux上执行的内部机制，但群晖是个定制系统出现了不兼容，已知问题给的建议是换用docker。

再说，这个错误看上去跟可执行好像没什么关系，如果你说的方法可行，那就加到计划任务里，启动时运行一下，也算是个解决方案了。

```
/tmp/mm-exhelper.so.WV5XqM.so: cannot open shared object file: No such file or directory
```

**Comment by fenghuaw** [comment]
群晖emby套件无法使用中文搜索解决方法：
登录到群晖管理界面，进入控制面板 -- 任务计划，新增 -- 触发的任务 -- 用户自定义脚本 -- 任务名称：Strm Assistant — 事件：开机 -- 任务设置 — 用户定义脚本
在用户定义的脚本中输入以下内容：mount -o remount,exec /tmp

**Comment by CleverMod** [comment]
请问绿联也出现了 魔改失败，请启用调试模式日志，重启后查看日志排查问题,  中文搜索增强无法开启, 如何解决
