### ISSUE TITLE
无法通过”类标题(别名)”来搜索影片

### ISSUE THREAD

**Issue by Goooooooooood** [sjtuross/StrmAssistant#7]
首先，非常感谢作者提供的中文搜索功能，真的非常好用！单字搜索、首字母拼音搜索都很棒，已经超过了小秘魔改dll。

使用了几天下来，发现一个问题，那就是无法通过“类标题(别名)”，来搜索影片了。

由于大陆片名与港台或新马地区翻译不同，以前是通过“类标题”来保留不同译名，以实现用不同译名都能搜到影片。(如下图所示)
![IMG_6555](https://github.com/user-attachments/assets/d70c4f27-32de-4111-aa0b-1a57f5f7883c)

如果可以实现对“类标题”的搜索，那就完美了！不知实现起来是否有难度。

期待，再次感谢。

**Comment by sjtuross** [comment]
这个类标题并不是这个用途，而且翻译有误，英语字段名称为`SortName`，正确的翻译应该叫“排序名”，是用来按名称排序用的。

原生搜索也不包含这个字段，只有标题和原标题会被纳入搜索，所以我不清楚你是怎么搜类标题的，可能是小秘版的功能之一。

全文索引不包含这个字段，如果强行添加，还需要魔改所有增删改查的地方，先不说是否能实现，但很可能会带来意料之外的bug

基于以上这些，我不会考虑这个需求，望理解。

**Comment by Goooooooooood** [comment]
> 这个类标题并不是这个用途，而且翻译有误，英语字段名称为`SortName`，正确的翻译应该叫“排序名”，是用来按名称排序用的。
> 
> 原生搜索也不包含这个字段，只有标题和原标题会被纳入搜索，所以我不清楚你是怎么搜类标题的，可能是小秘版的功能之一。
> 
> 全文索引不包含这个字段，如果强行添加，还需要魔改所有增删改查的地方，先不说是否能实现，但很可能会带来意料之外的bug
> 
> 基于以上这些，我不会考虑这个需求，望理解。

感谢答疑解惑。

能做到目前这样，已经非常棒了！

早就点了🌟，除了感谢还能说什么呢🙏。
