### ISSUE TITLE
套件版本使用BUG

### ISSUE THREAD

**Issue by csanmm887123** [sjtuross/StrmAssistant#8]
我用是arm的黑群，用的矿神版的破解套件，装大佬这个插件一大半的选项无法勾选。复选框亮的可勾选，暗的不可勾选。
![无标题](https://github.com/user-attachments/assets/e9166ad1-bfb8-4267-b9f0-fdb22e1d6dba)

**Comment by csanmm887123** [comment]
> 如果你看过Wiki就会知道魔改功能暂不支持arm平台，设置界面禁用相关选项是防呆设计。只要上游魔改平台的卡脖子bug解决就能支持 [MonoMod/MonoMod#90](https://github.com/MonoMod/MonoMod/issues/90) 但短期内只能换用x64平台

谢谢大佬解惑，我比较需要中文搜索加强和视频截图两个功能，尤其视频截图系统截图特别慢，大几百个视频根本出不来，除了你的这个作品还有其他可用的替代吗？

**Comment by sjtuross** [comment]
暂时没有，动态魔改实现这些功能应该是全网唯一了，替代就是换x64平台
