### ISSUE TITLE
原语言海报的功能是否有可能像获取tmdb元数据一样有优先级

### ISSUE THREAD

**Issue by LittleKa3235** [sjtuross/StrmAssistant#9]
问题主要出现在动画上，部分动画有官方的中文海报，而没有的tmdb默认会使用英文的海报，想看看能不能设置成有中文就优先中文，没有就优先原语言这样

**Comment by sjtuross** [comment]
原语言就是原语言优先，不存在中文优先的逻辑。如果你说的动画是国产的，那自然是中文海报，如果是日本的，就是日语海报。可能我没完全明白你说的，最好举个具体的例子。

**Comment by LittleKa3235** [comment]
啊，我指的获取tmdb原数据是 自定义 TMDB 备选语言 这个功能的实现一样自定义优先级
![QQ20241025-144238](https://github.com/user-attachments/assets/ce5e20a3-9019-492d-bc59-82842abbb91a)
比方说我现在默认方式刮削下来的媒体库，有中文海报使用的为中文海报，没有则使用的是英文海报，我的想法是能不能做到有中文海报的情况下使用中文海报，而没有的情况下根据原语言情况去获取（比如日本动画没有中文海报就是日语海报）

**Comment by sjtuross** [comment]
明白了，那这样好了，如果媒体库设置指定了首选图像下载语言，那就是第一优先级，没有就回退原语言。如果要完全原语言，那这个选项就不选。

![image](https://github.com/user-attachments/assets/d96a343e-cfa8-4722-ab79-dd24dbd98659)

**Comment by sjtuross** [comment]
新版已添加此逻辑，Wiki也同步更新了，你可以试试 https://github.com/sjtuross/StrmAssistant/releases/tag/v1.0.0.32

**Comment by LittleKa3235** [comment]
试了下，大部分都没问题了，有少数几部动画还是英文海报，我感觉跟tmdb那边有关系，总之我再试试先，十分感谢

**Comment by LittleKa3235** [comment]
哦我弄清楚了，目前没有的两部是因为日语那边没有符合条件的图片，那应该是没问题了，非常感谢
